import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Footer from "@/components/common/footer";
import Navbar from "@/components/common/navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Himpunan Mahasiswa Informatika (HMIF) UPNVJ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased min-h-[100dvh] w-full`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
